[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]
optimizer_runs = 1000000
no_match_test = "FFI"
solc="0.8.24"

# fuzz settings
[profile.default.fuzz]
runs=10000

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/${BASE_RPC_KEY}"